import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navigation } from '@/components/Navigation/Navigation';
import Hamburger from '@/components/Navigation/Hamburger';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className + `min-h-screen bg-blue-300`}>
				<Navigation />
				<Hamburger />
				<div className='h-screen '>{children}</div>
			</body>
		</html>
	);
}
